//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalRecordManagementAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Crime
    {
        public int Crime_ID { get; set; }
        [DisplayName("Crime"), Required]
        public string Crime_Name { get; set; }
        [DisplayName("Victim"), Required]
        public Nullable<int> Victim_id { get; set; }
        [DisplayName("Investigated by"), Required]
        public string Officer { get; set; }
        [DisplayName("Officer Position"), Required]
        public string Officer_Position { get; set; }

        public virtual Victim Victim { get; set; }
    }
}
