//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalRecordManagementAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    [Table("Criminal")]
    public partial class Criminal
    {
        public int Criminal_ID { get; set; }
        [DisplayName("Criminal"), Required]
        public string Criminal_Name { get; set; }
        public string Gender { get; set; }

        [DOBValidation]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        [DisplayName("Jail"), Required]
        public Nullable<int> Jail_id { get; set; }
        [DisplayName("Victim"), Required]
        public Nullable<int> Victim_id { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Jail Jail { get; set; }
        public virtual Victim Victim { get; set; }
    }
}
