//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalRecordManagementAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Net.Http;
    using System.Web.Mvc;

    public partial class User
    {
        public int User_ID { get; set; }
        [DisplayName("User Name"), Required]
        /*[Remote("IsUserNameAvailable", "Users", HttpMethod = "POST", ErrorMessage = "Username Exits")]*/
        public string User_Name { get; set; }

        [DisplayName("Password"), Required, StringLength(15, MinimumLength = 8, ErrorMessage = "should be from 8 to 15 chars")]
        public string User_Password { get; set; }
        public Nullable<int> Position_id { get; set; }

        public virtual Position Position { get; set; }
    }
}
