//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalRecordManagementAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    [Table("Victim")]
    public partial class Victim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Victim()
        {
            this.Crimes = new HashSet<Crime>();
            this.Criminals = new HashSet<Criminal>();
        }

        public int Victim_ID { get; set; }
        [DisplayName("Victim"), Required, StringLength(30, MinimumLength = 3, ErrorMessage = "Should be atleast 3 chars")]
        public string Victim_Name { get; set; }
        public string Gender { get; set; }
        [DataType(DataType.Date)]
        [DOBValidation]
        public Nullable<System.DateTime> DOB { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DODeath { get; set; }
        [DisplayName("Cause")]
        public string Cause_Of_Death { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crime> Crimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Criminal> Criminals { get; set; }
    }
}
